<div class="container">
    <?php
// within a view script
  
    $loginEmail = $this->loginForm->get('loginEmail');
    $loginPassword = $this->loginForm->get('loginPassword');
   // echo $formLabel->openTag() . $username->getOption('label');
   // echo $formLabel->closeTag();
    $loginEmailError = $this->formElementErrors($loginEmail);
    $loginPasswordError = $this->formElementErrors($loginPassword);
    ?>
    <form  action="<?php echo $this->basePath($this->loginForm->getAttribute('action')); ?>" method="<?php echo $this->loginForm->getAttribute('method'); ?>" class="form-signin">
        <h2 class="form-signin-heading">Login</h2>
        
        <div class="form-group <?php if($loginEmailError)echo 'has-error'; ?>">
            <label for="inputEmail" class="sr-only">Email</label>
            <!--input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email " required autofocus-->
            <?php echo $this->formInput($this->loginForm->get('loginEmail')); ?>
            <div class="help-block with-errors">
            <?php  echo $loginEmailError;?>   
            </div>
        </div>
        
        <div class="form-group <?php if($loginPasswordError)echo 'has-error'; ?>">
            <label for="inputPassword" class="sr-only">Password</label>
            <!--input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required-->
            <?php echo $this->formInput($loginPassword); ?>
             <div class="help-block with-errors">
            <?php  echo $loginPasswordError;?>   
            </div>
        </div>
        <div class="form-group ">
            <div class="checkbox">
                <label>
                    <?php echo $this->formInput($this->loginForm->get('loginRecordad')); ?> Recordar
                </label>
            </div>
        </div>

        <?php echo $this->formInput($this->loginForm->get('loginSubmit')); ?>
        <!--button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button-->
    </form>

</div> <!-- /container -->
