
<?php //var_dump($this->products); ?>
<div class="row outer-bottom-sm">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-3 sidebar">
            <!-- ================================== TOP NAVIGATION ================================== -->
            <div class="side-menu side-menu2 animate-dropdown outer-bottom-xs">
                <strong>Module:</strong>        Catalog &raquo;
                <strong>Controller:</strong>    Index &raquo;
                <strong>Action:</strong>        index

            </div>
        </div>
        <div class='col-md-9'>
            <!-- ========================================== SECTION – HERO ========================================= -->

            <div id="category" class="category-carousel hidden-xs">
                <div class="item">	
                    <div class="image">
                        <img src="<?php echo $this->basePath('assets') ?>/images/banners/cat-banner-1.jpg" alt="" class="img-responsive">
                    </div>
                    <!--div class="container-fluid">
                        <div class="caption vertical-top text-left">
                            <div class="big-text">
                                Sale
                            </div>

                            <div class="excerpt hidden-sm hidden-md">
                                up to 50% off
                            </div>

                        </div>
                    </div-->
                </div>
            </div>
            <!-- ========================================== SECTION – HERO - END ========================================= -->


            <!-- ========================================== Filtros ========================================= -->
            <div class="clearfix filters-container m-t-10">
                <div class="row">
                    <div class="col col-sm-6 col-md-2">
                        <div class="filter-tabs">
                            <ul id="filter-tabs" class="nav nav-tabs nav-tab-box nav-tab-fa-icon">
                                <li class="active">
                                    <a data-toggle="tab" href="#grid-container"><i class="icon fa fa-th-list"></i>Grid</a>
                                </li>
                                <li><a data-toggle="tab" href="#list-container"><i class="icon fa fa-th"></i>Lista</a></li>
                            </ul>
                        </div><!-- /.filter-tabs -->
                    </div><!-- /.col -->
                    <div class="col col-sm-12 col-md-6">
                        <div class="col col-sm-3 col-md-7 no-padding">
                            <div class="lbl-cnt">
                                <span class="lbl">Mostrar por</span>
                                <div class="fld inline">
                                    <div class="dropdown dropdown-small dropdown-med dropdown-white inline">
                                        <button data-toggle="dropdown" type="button" class="btn dropdown-toggle">
                                            Relevancia <span class="caret"></span>
                                        </button>

                                        <ul role="menu" class="dropdown-menu">

                                            <li role="presentation"><a href="#">Menor Precio</a></li>
                                            <li role="presentation"><a href="#">Mayor Precio</a></li>
                                            <li role="presentation"><a href="#">Destacados</a></li>
                                        </ul>
                                    </div>
                                </div><!-- /.fld -->
                            </div><!-- /.lbl-cnt -->
                        </div><!-- /.col -->
                        <div class="col col-sm-3 col-md-5 no-padding">
                            <div class="lbl-cnt">
                                <span class="lbl">Items</span>
                                <div class="fld inline">
                                    <div class="dropdown dropdown-small dropdown-med dropdown-white inline">
                                        <button data-toggle="dropdown" type="button" class="btn dropdown-toggle">
                                            1 <span class="caret"></span>
                                        </button>

                                        <ul role="menu" class="dropdown-menu">
                                            <li role="presentation"><a href="#">1</a></li>
                                            <li role="presentation"><a href="#">2</a></li>
                                            <li role="presentation"><a href="#">3</a></li>
                                            <li role="presentation"><a href="#">4</a></li>
                                            <li role="presentation"><a href="#">5</a></li>
                                            <li role="presentation"><a href="#">6</a></li>
                                            <li role="presentation"><a href="#">7</a></li>
                                            <li role="presentation"><a href="#">8</a></li>
                                            <li role="presentation"><a href="#">9</a></li>
                                            <li role="presentation"><a href="#">10</a></li>
                                        </ul>
                                    </div>
                                </div><!-- /.fld -->
                            </div><!-- /.lbl-cnt -->
                        </div><!-- /.col -->
                    </div><!-- /.col -->
                    <div class="col col-sm-6 col-md-4 text-right">
                        <div class="pagination-container">
                            <ul class="list-inline list-unstyled">
                                <li class="prev"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                <li><a href="#">1</a></li>	
                                <li class="active"><a href="#">2</a></li>	
                                <li><a href="#">3</a></li>	
                                <li><a href="#">4</a></li>	
                                <li class="next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            </ul><!-- /.list-inline -->
                        </div><!-- /.pagination-container -->		</div><!-- /.col -->
                </div><!-- /.row -->
            </div>
            <!-- ========================================== Filtros END ========================================= -->

            <!-- ============================ Search ========================================= -->
            <div class="search-result-container">
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane active " id="grid-container">
                        <div class="category-product  inner-top-vs">
                            <div class="row">

                                <?php foreach ($this->products as $product) : ?>
                                  
                                    <div class="col-sm-6 col-md-4 wow fadeInUp">
                                        <div class="products">

                                            <div class="product">		
                                                <div class="product-image">
                                                    <div class="image">
                                                        <a href="<?php echo $this->basePath().'/catalogo/'.$product->getUrlAlias()->keyword;?>">
                                                            <img class=" img-responsive"  src="<?php echo $this->basePath('assets') ?>/images/<?php echo $product->getImage();?>" data-echo="<?php echo $this->basePath('assets') ?>/images/products/<?php echo $product->getImage();?>" alt="">
                                                        </a>
                                                    </div><!-- /.image -->			
                                                    <!--div class="tag new"><span>nuevo</span></div-->                        		   
                                                </div><!-- /.product-image -->


                                                <div class="product-info text-left">
                                                    <h3 class="name"><a href="#">
                                                        <?php echo $product->getProductDescription()->getName();?>
                                                        </a></h3>
                                                    <div class="rating rateit-small"></div>
                                                    <div class="description"></div>

                                                    <div class="product-price">	
                                                        <span class="price">
                                                            <?php echo $product->getPrice() ?>				
                                                        </span>
                                                        <!--span class="price-before-discount">$ </span-->

                                                    </div><!-- /.product-price -->

                                                </div><!-- /.product-info -->
                                                <div class="cart clearfix animate-effect">
                                                    <div class="action">
                                                        <ul class="list-unstyled">
                                                            <li class="add-cart-button btn-group">
                                                                <button class="btn btn-primary icon" data-toggle="dropdown" type="button">
                                                                    <i class="fa fa-shopping-cart"></i>													
                                                                </button>
                                                                <button class="btn btn-primary" type="button">Comprar</button>

                                                            </li>

                                                            <li class="lnk wishlist">
                                                                <a class="add-to-cart" href="#" title="Wishlist">
                                                                    <i class="icon fa fa-heart"></i>
                                                                </a>
                                                            </li>

                                                            <li class="lnk">
                                                                <a class="add-to-cart" href="#" title="Compare">
                                                                    <i class="fa fa-retweet"></i>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div><!-- /.action -->
                                                </div><!-- /.cart -->
                                            </div><!-- /.product -->

                                        </div><!-- /.products -->
                                    </div><!-- /.item -->
  
                                <?php endforeach; ?>    
                                
                                
                            </div><!-- /.row -->
                        </div><!-- /.category-product -->

                    </div><!-- /.tab-pane -->

                    <div class="tab-pane "  id="list-container">
                        <div class="category-product  inner-top-vs">

                         <?php foreach ($this->products2 as $product2) : ?>       
                            <div class="category-product-inner wow fadeInUp">
                                <div class="products">				
                                    <div class="product-list product">
                                        <div class="row product-list-row">
                                            <div class="col col-sm-4 col-lg-4">
                                                <div class="product-image">
                                                    <div class="image">
                                                        <img data-echo="<?php echo $this->basePath('assets') ?>/images/products/c1.jpg" src="<?php echo $this->basePath('assets') ?>/images/blank.gif" alt="">
                                                    </div>
                                                </div><!-- /.product-image -->
                                            </div><!-- /.col -->
                                            <div class="col col-sm-8 col-lg-8">
                                                <div class="product-info">
                                                    <h3 class="name"><a href="#"><?php echo $product2->getProductDescription()->getName();?></a></h3>
                                                    <div class="rating rateit-small"></div>
                                                    <div class="product-price">	
                                                        <span class="price">
                                                             <?php echo $product2->getPrice() ?>					</span>
                                                        <!--span class="price-before-discount">$ 800</span-->

                                                    </div><!-- /.product-price -->
                                                    <div class="description m-t-10"><?php echo $product2->getProductDescription()->getDescription();?></div>
                                                    <div class="cart clearfix animate-effect">
                                                        <div class="action">
                                                            <ul class="list-unstyled">
                                                                <li class="add-cart-button btn-group">
                                                                    <button class="btn btn-primary icon" data-toggle="dropdown" type="button">
                                                                        <i class="fa fa-shopping-cart"></i>													
                                                                    </button>
                                                                    <button class="btn btn-primary" type="button">Comprar</button>

                                                                </li>

                                                                <li class="lnk wishlist">
                                                                    <a class="add-to-cart" href="#" title="Wishlist">
                                                                        <i class="icon fa fa-heart"></i>
                                                                    </a>
                                                                </li>

                                                                <li class="lnk">
                                                                    <a class="add-to-cart" href="#" title="Compare">
                                                                        <i class="fa fa-retweet"></i>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div><!-- /.action -->
                                                    </div><!-- /.cart -->

                                                </div><!-- /.product-info -->	
                                            </div><!-- /.col -->
                                        </div><!-- /.product-list-row -->
                                        <div class="tag new"><span>nuevo</span></div>        </div><!-- /.product-list -->
                                </div><!-- /.products -->
                            </div><!-- /.category-product-inner -->

                          <?php endforeach; ?>

                        </div><!-- /.category-product -->
                    </div><!-- /.tab-pane #list-container -->
                </div><!-- /.tab-content -->
                <div class="clearfix filters-container">

                    <div class="text-right">
                        <div class="pagination-container">
                            <ul class="list-inline list-unstyled">
                                <li class="prev"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                <li><a href="#">1</a></li>	
                                <li class="active"><a href="#">2</a></li>	
                                <li><a href="#">3</a></li>	
                                <li><a href="#">4</a></li>	
                                <li class="next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            </ul><!-- /.list-inline -->
                        </div><!-- /.pagination-container -->						    </div><!-- /.text-right -->

                </div><!-- /.filters-container -->

            </div><!-- /.search-result-container -->


            <!-- ============================ Search - End ========================================= -->

        </div>
    </div>
</div>


