<!-- ============================================================= FOOTER ============================================================= -->
        <footer id="footer" class="footer color-bg" >
            <div class="links-social inner-top-sm">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <!-- ============================================================= CONTACT INFO ============================================================= -->
                            <div class="contact-info">
                                <div class="footer-logo">
                                    <div class="logo">
                                        <a href="#">

                                            <img src="<?php echo $this->basePath('assets') ?>/images/lakari-logo-footer.png" alt="">

                                        </a>
                                    </div><!-- /.logo -->

                                </div><!-- /.footer-logo -->

                                <div class="module-body m-t-20">
                                    <p class="about-us">La mejor opción para amueblar y decorar tu hogar, productos de calidad con atencion insuperables.</p>

                                    <div class="social-icons">

                                        <a href="#" class='active'><i class="icon fa fa-facebook"></i></a>
                                        <a href="#"><i class="icon fa fa-twitter"></i></a>
                                        <a href="#"><i class="icon fa fa-linkedin"></i></a>
                                        <a href="#"><i class="icon fa fa-rss"></i></a>
                                        <a href="#"><i class="icon fa fa-pinterest"></i></a>

                                    </div><!-- /.social-icons -->
                                </div><!-- /.module-body -->

                            </div><!-- /.contact-info -->
                            <!-- ============================================================= CONTACT INFO : END ============================================================= -->            	</div><!-- /.col -->

                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <!-- ============================================================= CONTACT TIMING============================================================= -->
                            <div class="contact-timing">
                                <div class="module-heading">
                                    <h4 class="module-title">Horarios</h4>
                                </div><!-- /.module-heading -->

                                <div class="module-body outer-top-xs">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <tbody>
                                                <tr><td>Lunes-Viernes:</td><td class="pull-right">08.00 a 18.00</td></tr>
                                                <tr><td>Sabados:</td><td class="pull-right">09.00 a 20.00</td></tr>
                                                <tr><td>Domingo:</td><td class="pull-right">10.00 a 20.00</td></tr>
                                            </tbody>
                                        </table>
                                    </div><!-- /.table-responsive -->
                                    <p class='contact-number'>Atención al cliente:(400)888 868 848</p>
                                </div><!-- /.module-body -->
                            </div><!-- /.contact-timing -->
                            <!-- ============================================================= CONTACT TIMING : END ============================================================= -->            	</div><!-- /.col -->

                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <!-- ============================================================= LATEST TWEET============================================================= -->
                            <div class="latest-tweet">
                                <div class="module-heading">
                                    <h4 class="module-title">Últimos tweet</h4>
                                </div><!-- /.module-heading -->

                                <div class="module-body outer-top-xs">
                                    <div class="re-twitter">
                                        <div class="comment media">
                                            <div class='pull-left'>
                                                <span class="icon fa-stack fa-lg">
                                                    <i class="fa fa-circle fa-stack-2x"></i>
                                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </div>
                                            <div class="media-body">
                                                <a href="#">@lakari</a> 100% recomendado :) 
                                                <span class="time">
                                                    12 hours ago
                                                </span>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="re-twitter">
                                        <div class="comment media">
                                            <div class='pull-left'>
                                                <span class="icon fa-stack fa-lg">
                                                    <i class="fa fa-circle fa-stack-2x"></i>
                                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </div>
                                            <div class="media-body">
                                                <a href="#">@lakari</a> 100% recomendado :) 
                                                <span class="time">
                                                    12 hours ago
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- /.module-body -->
                            </div><!-- /.contact-timing -->
                            <!-- ============================================================= LATEST TWEET : END ============================================================= -->            	</div><!-- /.col -->

                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <!-- ============================================================= INFORMATION============================================================= -->
                            <div class="contact-information">
                                <div class="module-heading">
                                    <h4 class="module-title">información</h4>
                                </div><!-- /.module-heading -->

                                <div class="module-body outer-top-xs">
                                    <ul class="toggle-footer" style="">
                                        <li class="media">
                                            <div class="pull-left">
                                                <span class="icon fa-stack fa-lg">
                                                    <i class="fa fa-circle fa-stack-2x"></i>
                                                    <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </div>
                                            <div class="media-body">
                                                <p>868 Any Stress,Burala Casi,Picasa USA.</p>
                                            </div>
                                        </li>

                                        <li class="media">
                                            <div class="pull-left">
                                                <span class="icon fa-stack fa-lg">
                                                    <i class="fa fa-circle fa-stack-2x"></i>
                                                    <i class="fa fa-mobile fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </div>
                                            <div class="media-body">
                                                <p>(400) 0888 888 888<br>(400) 888 888 888</p>
                                            </div>
                                        </li>

                                        <li class="media">
                                            <div class="pull-left">
                                                <span class="icon fa-stack fa-lg">
                                                    <i class="fa fa-circle fa-stack-2x"></i>
                                                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </div>
                                            <div class="media-body">
                                                <span><a href="#">Contacto @lakarihome.com</a></span><br>
                                                <span><a href="#">Ventas @lakarihome.com</a></span>
                                            </div>
                                        </li>

                                    </ul>
                                </div><!-- /.module-body -->
                            </div><!-- /.contact-timing -->
                            <!-- ============================================================= INFORMATION : END ============================================================= -->            	</div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container -->
            </div><!-- /.links-social -->

            <div class="footer-bottom inner-bottom-sm">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="module-heading outer-bottom-xs">
                                <h4 class="module-title">Lo Más Buscado</h4>
                            </div><!-- /.module-heading -->

                            <div class="module-body">
                                <ul class='list-unstyled'>
                                    <li><a href="#">Accesorios de Baño</a></li>
                                    <li><a href="#">Griferia</a></li>
                                    <li><a href="#">Fregaderos</a></li>
                                    <li><a href="#">Bañeras</a></li>
                                    <li><a href="#">Calentadores</a></li>
                                </ul>
                            </div><!-- /.module-body -->
                        </div><!-- /.col -->

                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="module-heading outer-bottom-xs">
                                <h4 class="module-title">Información</h4>
                            </div><!-- /.module-heading -->

                            <div class="module-body">
                                <ul class='list-unstyled'>
                                   
                                    <li><a href="#">Servicio al Cliente</a></li>
                                    <li><a href="#">Politica de privacidad</a></li>
                                    <li><a href="#">Mapa del Sitio</a></li>
                                    <li><a href="#">Terminos y Condiciones</a></li>
                                </ul>
                            </div><!-- /.module-body -->
                        </div><!-- /.col -->

                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="module-heading outer-bottom-xs">
                                <h4 class="module-title">Mi cuenta</h4>
                            </div><!-- /.module-heading -->

                            <div class="module-body">
                                <ul class='list-unstyled'>
                                    <li><a href="#">Historial de pedidos</a></li>
                                    <li><a href="#">Devoluciones</a></li>
                                    <li><a href="#">Regalos</a></li>
                                </ul>
                            </div><!-- /.module-body -->
                        </div><!-- /.col -->

                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="module-heading outer-bottom-xs">
                                <h4 class="module-title">Ayuda y soporte</h4>
                            </div><!-- /.module-heading -->

                            <div class="module-body">
                                <ul class='list-unstyled'>  
                                    <li><a href="#">Chat</a></li>
                                    <li><a href="#">Contactarnos</a></li>
                                    <li><a href="#">Noticias y Tips</a></li>
                                    <li><a href="#">Acerca de LakariHome</a></li>
                                </ul>
                            </div><!-- /.module-body -->
                        </div>
                    </div>
                </div>
            </div>

            <div class="copyright-bar">
                <div class="container">
                    <div class="col-xs-12 col-sm-6 no-padding">
                        <div class="copyright">
                            Copyright © 2015
                            <a href="#">LakariHome.com</a>
                            - Todos los derechos reservados
                            <span style="margin-left: 20px">Desarrollado por <a href="#" style="color: #CCC">Gimalca</a></span>
                        </div>
                        
                    </div>
                    <div class="col-xs-12 col-sm-6 no-padding">
                        <div class="clearfix payment-methods">
                            <ul>
                                <li><img src="<?php echo $this->basePath('assets') ?>/images/payments/1.png" alt=""></li>
                                <li><img src="<?php echo $this->basePath('assets') ?>/images/payments/2.png" alt=""></li>
                                <li><img src="<?php echo $this->basePath('assets') ?>/images/payments/3.png" alt=""></li>
                                <li><img src="<?php echo $this->basePath('assets') ?>/images/payments/4.png" alt=""></li>
                                <li><img src="<?php echo $this->basePath('assets') ?>/images/payments/5.png" alt=""></li>
                            </ul>
                        </div><!-- /.payment-methods -->
                    </div>
                </div>
            </div>
        </footer>
        <!-- ============================================================= FOOTER : END============================================================= -->