
<head>
        <!-- Meta -->
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
        ?>
     
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="keywords" content="MediaCenter, Template, eCommerce">
        <meta name="robots" content="all">

        <title>.:: Lakari Home ::.</title>
         <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/bootstrap.min.css">

        <!-- Customizable CSS -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/main.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/green.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/owl.carousel.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/owl.transitions.css">
        <!--<link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/owl.theme.css">-->
        <link href="<?php echo $this->basePath('assets') ?>/css/lightbox.css" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/animate.min.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/rateit.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/bootstrap-select.min.css">

        <!-- Demo Purpose Only. Should be removed in production -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/config.css">

        <link href="<?php echo $this->basePath('assets') ?>/css/green.css" rel="alternate stylesheet" title="Green color">
        <link href="<?php echo $this->basePath('assets') ?>/css/blue.css" rel="alternate stylesheet" title="Blue color">
        <link href="<?php echo $this->basePath('assets') ?>/css/red.css" rel="alternate stylesheet" title="Red color">
        <link href="<?php echo $this->basePath('assets') ?>/css/orange.css" rel="alternate stylesheet" title="Orange color">
        <link href="<?php echo $this->basePath('assets') ?>/css/dark-green.css" rel="alternate stylesheet" title="Darkgreen color">
        <!-- Demo Purpose Only. Should be removed in production : END -->


        <!-- Icons/Glyphs -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/font-awesome.min.css">

        <!-- Fonts --> 
        <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>

        <!-- Favicon -->
        <link rel="shortcut icon" href="<?php echo $this->basePath('assets') ?>/images/favicon.ico">

        <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
        <!--[if lt IE 9]>
                <script src="<?php echo $this->basePath('assets') ?>/js/html5shiv.js"></script>
                <script src="<?php echo $this->basePath('assets') ?>/js/respond.min.js"></script>
        <![endif]-->

    </head>