 <!-- ============================================== HEADER ============================================== -->
        <header class="header-style-1 header-style-2">

            <!-- ============================================== TOP MENU ============================================== -->
            <div class="top-bar animate-dropdown">
                <div class="container">
                    <div class="header-top-inner">
                        <div class="cnt-account">
                            <ul class="list-unstyled">
                                <li><a href="#"><i class="icon fa fa-user"></i>Mi Cuenta</a></li>
                                <li><a href="#"><i class="icon fa fa-heart"></i>Lista</a></li>
                                <li><a href="#"><i class="icon fa fa-shopping-cart"></i>Mi Compra</a></li>
                                <!--li><a href="#"><i class="icon fa fa-key"></i>Checkout</a></li-->
                                <li><a href="#"><i class="icon fa fa-sign-in"></i>Login</a></li>
                                <li style="padding:0">
                                    <div id="fb-root"></div>
                                    <script>(function (d, s, id) {
                                            var js, fjs = d.getElementsByTagName(s)[0];
                                            if (d.getElementById(id))
                                                return;
                                            js = d.createElement(s);
                                            js.id = id;
                                            js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&appId=617402458348371&version=v2.0";
                                            fjs.parentNode.insertBefore(js, fjs);
                                        }(document, 'script', 'facebook-jssdk'));</script>

                                    <div class="fb-login-button" data-max-rows="1" data-size="small" data-show-faces="false" data-auto-logout-link="false"></div>
                                </li>
                            </ul>
                        </div>
                        <div class="cnt-block">
                            <ul class="list-unstyled list-inline">
                                <li class="dropdown dropdown-small">
                                    <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"><span class="key">Moneda :</span><span class="value">USD </span><b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">USD</a></li>
                                        <li><a href="#">BS</a></li>
                                        <li><a href="#">PESO colombiano</a></li>
                                    </ul>
                                </li>

                                <li class="dropdown dropdown-small">
                                    <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"><span class="key">Idioma :</span><span class="value">Español </span><b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">English</a></li>

                                    </ul>
                                </li>
                            </ul><!-- /.list-unstyled -->
                        </div><!-- /.cnt-cart -->
                        <div class="clearfix"></div>
                    </div><!-- /.header-top-inner -->
                </div><!-- /.container -->
            </div><!-- /.header-top -->
            <!-- ============================================== TOP MENU : END ============================================== -->
            <div class="main-header">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-3 logo-holder">
                            <!-- ============================================================= LOGO ============================================================= -->
                            <div class="logo">
                                <a href="<?php echo $this->url('home') ?>">

                                    <img src="<?php echo $this->basePath('assets') ?>/images/lakari-logo.png" alt="">

                                </a>
                            </div><!-- /.logo -->
                            <!-- ============================================================= LOGO : END ============================================================= -->				</div><!-- /.logo-holder -->

                        <div class="col-xs-12 col-sm-12 col-md-6 top-search-holder">
                            <div class="contact-row">
                                <div class="phone inline">
                                    <i class="icon fa fa-phone"></i> (400) 888 888 868
                                </div>
                                <div class="phone inline">
                                    <i class="icon fa fa-envelope"></i> info@lakari.com
                                </div>
                                <div class="contact inline">
                                    <a href="#">
                                        <i class="icon fa fa-hand-o-right"></i><span style="color: red; font-weight: 500">VENDE EN LÁKARI</span>
                                    </a>
                                </div>
                            </div><!-- /.contact-row -->
                            <!-- ============================================================= SEARCH AREA ============================================================= -->
                            <div class="search-area">
                                <form>
                                    <div class="control-group">

                                        <ul class="categories-filter animate-dropdown">
                                            <li class="dropdown">

                                                <a class="dropdown-toggle"  data-toggle="dropdown" href="#">Categoria <b class="caret"></b></a>

                                                <ul class="dropdown-menu" role="menu" >
                                                    <li class="menu-header">Buscar por</li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">- Articulo</a></li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">- Categoría</a></li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">- Servicios</a></li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">- Marca</a></li>

                                                </ul>
                                            </li>
                                        </ul>

                                        <input class="search-field" placeholder="Buscar..." />

                                        <a class="search-button" href="#" ></a>    

                                    </div>
                                </form>
                            </div><!-- /.search-area -->
                            <!-- ============================================================= SEARCH AREA : END ============================================================= -->				</div><!-- /.top-search-holder -->

                        <div class="col-xs-12 col-sm-12 col-md-3 animate-dropdown top-cart-row">
                            <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->

                            <div class="dropdown dropdown-cart">
                                <a href="#" class="dropdown-toggle lnk-cart" data-toggle="dropdown">
                                    <div class="items-cart-inner">
                                        <div class="total-price-basket">
                                            <span class="lbl">MI COMPRA -</span>
                                            <span class="total-price">
                                                <span class="sign">$</span>
                                                <span class="value">600.00</span>
                                            </span>
                                        </div>
                                        <div class="basket">
                                            <i class="glyphicon glyphicon-shopping-cart"></i>
                                        </div>
                                        <div class="basket-item-count"><span class="count">2</span></div>

                                    </div>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <div class="cart-item product-summary">
                                            <div class="row">
                                                <div class="col-xs-4">
                                                    <div class="image">
                                                        <a href="#"><img src="<?php echo $this->basePath('assets') ?>/images/cart.jpg" alt=""></a>
                                                    </div>
                                                </div>
                                                <div class="col-xs-7">

                                                    <h3 class="name"><a href="#">Simple Producto</a></h3>
                                                    <div class="price">$600.00</div>
                                                </div>
                                                <div class="col-xs-1 action">
                                                    <a href="#"><i class="fa fa-trash"></i></a>
                                                </div>
                                            </div>
                                        </div><!-- /.cart-item -->
                                        <div class="clearfix"></div>
                                        <hr>

                                        <div class="clearfix cart-total">
                                            <div class="pull-right">

                                                <span class="text">Sub Total :</span><span class='price'>$600.00</span>

                                            </div>
                                            <div class="clearfix"></div>

                                            <a href="#" class="btn btn-upper btn-primary btn-block m-t-20">Sumario</a>	
                                        </div><!-- /.cart-total-->


                                    </li>
                                </ul><!-- /.dropdown-menu-->
                            </div><!-- /.dropdown-cart -->

                            <!-- ============================================================= SHOPPING CART DROPDOWN : END============================================================= -->				</div><!-- /.top-cart-row -->
                    </div><!-- /.row -->

                </div><!-- /.container -->

            </div><!-- /.main-header -->

            <!-- ============================================== NAVBAR ============================================== -->
            <div class="header-nav animate-dropdown">
                <div class="container">
                    <div class="yamm navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="nav-bg-class">
                            <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
                                <div class="nav-outer">
                                    <ul class="nav navbar-nav">
                                        <li class="active dropdown yamm-fw">
                                            <a href="#" data-hover="dropdown" class="dropdown-toggle" data-toggle="dropdown">INICIO</a>
                                            
                                        </li>

                                        <li class="dropdown">

                                            <a href="#">Muebles
                                                <span class="menu-label hot-menu hidden-xs">Ofertas</span>
                                            </a>
                                        </li>

                                        <li class="dropdown">

                                            <a href="#">Griferías

                                            </a>
                                        </li>
                                        <li class="dropdown hidden-sm">

                                            <a href="#">Iluminación
                                                <span class="menu-label new-menu hidden-xs">Nuevo</span>
                                            </a>
                                        </li>
                                        <li class="dropdown hidden-sm">

                                            <a href="#">Utensilios

                                            </a>
                                        </li>

                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">Servicios</a>
                                            <ul class="dropdown-menu pages">
                                                <li>
                                                    <div class="yamm-content">
                                                        <div class="row">

                                                            <div class='col-xs-12 col-sm-4 col-md-4'>
                                                                <ul class='links'>
                                                                    <li><a href="#">Plomería</a></li>
                                                                    <li><a href="#">Instalación </a></li>
                                                                    <li><a href="#">Fumigación</a></li>
                                                                    <li><a href="#">Limpieza</a></li>
                                                                    <li><a href="#">Electricidad</a></li>
                                                                    <li><a href="#">Pintura</a></li>
                                                                   

                                                                </ul>
                                                            </div>
                                                            

                                                        </div>
                                                    </div>
                                                </li>


                                            </ul>
                                        </li>


                                    </ul><!-- /.navbar-nav -->
                                    <div class="clearfix"></div>				
                                </div><!-- /.nav-outer -->
                            </div><!-- /.navbar-collapse -->


                        </div><!-- /.nav-bg-class -->
                    </div><!-- /.navbar-default -->
                </div><!-- /.container-class -->

            </div><!-- /.header-nav -->
            <!-- ============================================== NAVBAR : END ============================================== -->

        </header>

        <!-- ============================================== HEADER : END ============================================== -->