<?php echo $this->doctype(); ?>

<html lang="en">
    <?php echo $this->partial('layout/head'); ?>

    <body class="cnt-home">
        <?php echo $this->partial('layout/header'); ?>
        <div class="body-content outer-top-xs" id="top-banner-and-menu">
            <div class="container">
                <?php echo $this->content; ?>
            </div>
        </div>
        <?php echo $this->partial('layout/footer'); ?>
        
        <?php echo $this->inlineScript() ?>



        <!-- JavaScripts placed at the end of the document so the pages load faster -->
        <script src="<?php echo $this->basePath('assets') ?>/js/jquery-1.11.1.min.js"></script>

        <script src="<?php echo $this->basePath('assets') ?>/js/bootstrap.min.js"></script>

        <script src="<?php echo $this->basePath('assets') ?>/js/bootstrap-hover-dropdown.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/owl.carousel.min.js"></script>

        <script src="<?php echo $this->basePath('assets') ?>/js/echo.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/jquery.easing-1.3.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/bootstrap-slider.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/jquery.rateit.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets') ?>/js/lightbox.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/bootstrap-select.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/wow.min.js"></script>
        <script src="<?php echo $this->basePath('assets') ?>/js/scripts.js"></script>
    </body>   




</html>